let
    Origen = Folder.Files("C:\Users\LICET\Downloads\copias para mod\Camaras"),
    #"Archivos ocultos filtrados1" = Table.SelectRows(Origen, each [Attributes]?[Hidden]? <> true),
    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo", each #"Transformar archivo"([Content])),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo"}),
    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo", Table.ColumnNames(#"Transformar archivo"(#"Archivo de ejemplo"))),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"objectid", Int64.Type}, {"shape", type text}, {"direccion", type text}, {"localizacion", type text}, {"link_foto", type text}, {"link_detalle", type text}, {"longitud", Int64.Type}, {"latitud", Int64.Type}, {"x_origen_nacional", Int64.Type}, {"y_origen_nacional", Int64.Type}}),
    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado",{"Source.Name", "objectid", "direccion", "localizacion", "link_foto", "link_detalle", "longitud", "latitud"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Otras columnas quitadas",{{"latitud", type number}, {"longitud", type number}, {"direccion", type text}}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado1","Ã","Á",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Ò","Ó",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Ê","É",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","TÁŠNEL DE OCCIDENTE","TUNEL DE OCCIDENTE",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","ZOOLÁ“GICO","ZOOLÓGICO",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Á‰XITO UNICENTRO","ÉXITO UNICENTRO",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","TUGÁ“","TUGÓ",Replacer.ReplaceText,{"localizacion"}),
    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Valor reemplazado6", {{"localizacion", "%"}}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Errores reemplazados","""","",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","%","",Replacer.ReplaceValue,{"localizacion"}),
    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","""","",Replacer.ReplaceValue,{"localizacion"}),
    #"Valor reemplazado10" = Table.ReplaceValue(#"Valor reemplazado9","CAI LÁ“PEZ DE MESA","CAI LOPEZ DE MESA",Replacer.ReplaceText,{"localizacion"}),
    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10","COLCAFÁ‰","COLCAFÉ",Replacer.ReplaceValue,{"localizacion"}),
    #"Valor reemplazado12" = Table.ReplaceValue(#"Valor reemplazado11","“","",Replacer.ReplaceValue,{"localizacion"}),
    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Valor reemplazado12", {{"localizacion", ""}}),
    #"Valor reemplazado13" = Table.ReplaceValue(#"Errores reemplazados1","POSTOBÁ“N","POSTOBÓN",Replacer.ReplaceText,{"localizacion"}),
    #"Filas filtradas" = Table.SelectRows(#"Valor reemplazado13", each ([longitud] <> null)),
    #"Texto limpio" = Table.TransformColumns(#"Filas filtradas",{{"direccion", Text.Clean, type text}}),
    #"Texto recortado" = Table.TransformColumns(#"Texto limpio",{{"direccion", Text.Trim, type text}})
in
    #"Texto recortado"