let
    Origen = Folder.Files("C:\Users\LICET\Downloads\copias para mod\Intensidad"),
    #"Archivos ocultos filtrados1" = Table.SelectRows(Origen, each [Attributes]?[Hidden]? <> true),
    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo", each #"Transformar archivo"([Content])),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo"}),
    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo", Table.ColumnNames(#"Transformar archivo"(#"Archivo de ejemplo"))),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"carril", type text}, {"fecha_trafico", type datetime}, {"fecha", type date}, {"hora", Int64.Type}, {"dia", type text}, {"dia_num", Int64.Type}, {"mes_num", Int64.Type}, {"mes", type text}, {"ano", Int64.Type}, {"velocidad_km_h", Int64.Type}, {"corredor", type text}, {"sentido", type text}, {"operacion", type text}, {"intensidad", Int64.Type}, {"categoria_1", Int64.Type}, {"categoria_2", Int64.Type}, {"categoria_3", Int64.Type}, {"ocupacion", Int64.Type}, {"tipo_subsistema", type text}, {"longitud", type number}, {"latitud", type number}, {"identificador_f_v", type text}, {"comuna", type text}, {"codigo_comuna", Int64.Type}, {"nombre_comuna", type text}}),
    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "fecha fix", each try Date.FromText(Text.From([fecha])) 
otherwise try Date.AddDays(#date(1899,12,30), Number.From([fecha])) 
otherwise null),
    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "fecha_nueva", each #date([ano],[mes_num],[dia_num])),
    #"Columnas quitadas1" = Table.RemoveColumns(#"Personalizada agregada1",{"fecha fix", "codigo_comuna"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas quitadas1",{{"ocupacion", type number}, {"fecha_nueva", type date}}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Tipo cambiado1",{"Source.Name", "fecha", "fecha_nueva", "hora", "dia", "mes", "velocidad_km_h", "corredor", "sentido", "operacion", "intensidad", "categoria_1", "categoria_2", "categoria_3", "ocupacion", "tipo_subsistema", "longitud", "latitud", "nombre_comuna"}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas reordenadas","","SIN INFORMACION",Replacer.ReplaceValue,{"sentido"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","","SIN INFORMACION",Replacer.ReplaceValue,{"operacion"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","SISTEMA VIAL DEL Rï¿½ï¿½ï¿½O","SISTEMA VIAL DEL RIO",Replacer.ReplaceText,{"nombre_comuna"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","SISTEMA VIAL DEL Rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½O","SISTEMA VIAL DEL RIO",Replacer.ReplaceText,{"nombre_comuna"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","CORREGIMIENTO DE SAN CRISTï¿½ï¿½ï¿½BAL","CORREGIMIENTO DE SAN CRISTOBAL",Replacer.ReplaceText,{"nombre_comuna"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","SISTEMA VIAL DEL Rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½O","SISTEMA VIAL DEL RIO",Replacer.ReplaceText,{"nombre_comuna"}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","NONE","COMUNA DESCONOCIDA",Replacer.ReplaceText,{"nombre_comuna"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Valor reemplazado6",{"fecha"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"fecha_nueva", "fecha"}}),
    #"Columnas reordenadas1" = Table.ReorderColumns(#"Columnas con nombre cambiado",{"fecha_trafico", "fecha", "hora", "dia", "dia_num", "mes_num", "ano", "mes", "velocidad_km_h", "corredor", "sentido", "operacion", "intensidad", "categoria_1", "categoria_2", "categoria_3", "ocupacion", "tipo_subsistema", "longitud", "identificador_f_v", "comuna", "latitud", "nombre_comuna"}),
    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Columnas reordenadas1", {"carril"}),
    #"Filas filtradas" = Table.SelectRows(#"Errores quitados", each ([carril] <> null)),
    #"Columnas quitadas2" = Table.RemoveColumns(#"Filas filtradas",{"Source.Name"}),
    #"Columnas reordenadas2" = Table.ReorderColumns(#"Columnas quitadas2",{"carril", "fecha_trafico", "fecha", "hora", "dia", "dia_num", "mes_num", "ano", "mes", "velocidad_km_h", "corredor", "sentido", "operacion", "intensidad", "categoria_1", "categoria_2", "categoria_3", "ocupacion", "identificador_f_v", "tipo_subsistema", "longitud", "latitud", "comuna", "nombre_comuna"}),
    #"Columnas quitadas3" = Table.RemoveColumns(#"Columnas reordenadas2",{"identificador_f_v"}),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas quitadas3",{{"velocidad_km_h", type number}}),
    #"Columnas quitadas4" = Table.RemoveColumns(#"Tipo cambiado2",{"carril"}),
    #"Índice agregado" = Table.AddIndexColumn(#"Columnas quitadas4", "Índice", 1, 1, Int64.Type),
    #"Columnas reordenadas3" = Table.ReorderColumns(#"Índice agregado",{"Índice", "fecha_trafico", "fecha", "hora", "dia", "dia_num", "mes_num", "ano", "mes", "velocidad_km_h", "corredor", "sentido", "operacion", "intensidad", "categoria_1", "categoria_2", "categoria_3", "ocupacion", "tipo_subsistema", "longitud", "latitud", "comuna", "nombre_comuna"}),
    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Columnas reordenadas3",{{"Índice", "id"}}),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas con nombre cambiado2",{{"id", Int64.Type}, {"longitud", type text}, {"latitud", type text}}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Tipo cambiado3",",",".",Replacer.ReplaceText,{"longitud", "latitud"}),
    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Valor reemplazado7",{{"longitud", type number}, {"latitud", type number}, {"velocidad_km_h", type text}}),
    #"Valor reemplazado8" = Table.ReplaceValue(#"Tipo cambiado4",",",".",Replacer.ReplaceText,{"velocidad_km_h"}),
    #"Tipo cambiado5" = Table.TransformColumnTypes(#"Valor reemplazado8",{{"velocidad_km_h", type number}})
in
    #"Tipo cambiado5"